version: "3.1"

services:
  mypage-db-service:
    container_name: mypage-db-service
    build: ./db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${MYPAGE_PG_USER}
      - POSTGRES_PASSWORD=${MYPAGE_PG_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  mypage-app-service:
    container_name: mypage-app-service
    build: ./
    volumes:
      - './app/:/nodeapp/app'
      - './db/:/nodeapp/db'
    command: nodemon server.js
    environment:
      - DATABASE_DEV_URL=${DATABASE_DEV_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - DATABASE_PROD_URL=${DATABASE_PROD_URL}
      - NODE_ENV=development
    depends_on:
      - mypage-db-service
  mypage-nginx-service:
    container_name: mypage-nginx-service
    build: ./nginx
    volumes:
      - './nginx/public:/usr/local/var/www/public'
    ports:
      - '443:443'
    depends_on:
      - mypage-app-service
