version: "3.1"

services:
  mypage-db-service:
    container_name: mypage-db-service
    restart: always
    build: ./db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${MYPAGE_PG_USER}
      - POSTGRES_PASSWORD=${MYPAGE_PG_PASSWORD}
    volumes:
      - ~/tmp/db:/var/lib/postgresql/data

  mypage-app-service:
    container_name: mypage-app-service
    restart: always
    build:
        context: .
        dockerfile: DockerfileProduction
    environment:
      - DATABASE_PROD_URL=${DATABASE_PROD_URL}
      - NODE_ENV=production
    depends_on:
      - mypage-db-service
  mypage-nginx-service:
    container_name: mypage-nginx-service
    restart: always
    build: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mypage-app-service
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
